### ISSUE TITLE
how to delete

### ISSUE THREAD

**Issue by memoir** [EXALAB/AnLinux-App#1]
Instructions or a script to delete an installed Linux FS would be great. I could just delete the `ubuntu_fs` folder, but I'm only getting a bunch of "Permission denied" errors when I try to delete the `centos_fs` folder.

**Comment by memoir** [comment]
Oh, OK, just needed write permissions on the directory. Anyway, automated uninstall would be good idea, I think.

**Comment by exalab999** [comment]
Simply modify the permission by running chown -R 777 <distro>-fs/* and run rm -rf <distro>_fs would delete the directory, I will considering adding uninstallation script in the future.

**Comment by tlgoa** [comment]
I tried to unistall by following the instructions you add. But i am getting error message:
 rm: can't remove 'de-apt.sh': No such file or directory
rm: can't remove 'de-apt-mate.sh': No such file or directory
rm: can't remove 'de-apt-lxqt.sh': No such file or directory
rm: can't remove 'de-apt-lxde.sh': No such file or directory
Help please

**Comment by exalab999** [comment]
@tlgoa The uninstall script would try to remove all script that used in the Linux system, but user might not install them so the install script will return these error. It could be igroned safely.
