### ISSUE TITLE
Gnome Desktop Environment??

### ISSUE THREAD

**Issue by josephworks** [EXALAB/AnLinux-App#10]
Please add.

**Comment by exalab999** [comment]
Gnome Desktop Environment is one of the most heavy DE available, it is also feature rich and some of them may not worked well on Android platform. For this reason, we are currently does not plan to support it, but this may change in the future.

**Comment by josephworks** [comment]
Ok, I agree. What about Cinnamon DE

Joseph R.

**Comment by exalab999** [comment]
Cinnamon is somewhat same as Gnome, or even heavier.

**Comment by josephworks** [comment]
What about mate or kde

**Comment by josephworks** [comment]
What about mate or kde

**Comment by exalab999** [comment]
Mate desktop environment is possible, it has been added to the testing list, KDE is once the most heavy DE, it is much lighter now, but still not possible.

**Comment by exalab999** [comment]
@josephworks 

Mate Desktop Environment is now supported in v4.5

**Comment by josephworks** [comment]
Thanks!

Joseph R.
