### ISSUE TITLE
openSUSE ARM not available

### ISSUE THREAD

**Issue by pbielefeldt** [EXALAB/AnLinux-App#101]
Hi folks!

I just checked out this project; But I was unable to install openSUSE (Leap) on my machine. My `dpkg --print-architecture` will result in "arm", which is not covered in [opensuse-leap.sh](https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/openSUSE/Leap/opensuse-leap.sh), cf. line 18. Is that on purpose? Afaik, openSUSE does have a [rootfs for arm](https://en.opensuse.org/openSUSE:OpenSUSE_on_your_ARM_board) of its operating system …?

Am I overlooking something here? 

Best regards!
Philipp

**Comment by exalab999** [comment]
Yes, Leap and Tumbleweed Docker image only available for x86 and arm64...
