### ISSUE TITLE
Can't enter any of my Linux anymore

### ISSUE THREAD

**Issue by Hyperscope35** [EXALAB/AnLinux-App#103]
This app has always been working fine, but recently I can't enter my Linux anymore...

This is the error that I'm getting:

proot warning: can't sanitize binding "kali-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/kali-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

EDIT: I cleaned the app cache and it works now

**Comment by exalab999** [comment]
This error always occur, but we are sure that has nothing to do with
AnLinux, maybe try to reinstall Termux would fix it?

**Comment by Hyperscope35** [comment]
Okay thanks

**Comment by akoveysi** [comment]
![Screenshot_۲۰۲۰۰۲۱۳-۰۸۰۸۵۹](https://user-images.githubusercontent.com/60853672/74401963-1d019700-4e38-11ea-9ffc-2d713489cad4.png)

**Comment by mangesh-g-d** [comment]
I'm facing same issue

**Comment by abhinavmukundh** [comment]
Same issue for me also
![Uploading 74401963-1d019700-4e38-11ea-9ffc-2d713489cad4.png…]()
