### ISSUE TITLE
Sudo error

### ISSUE THREAD

**Issue by Th3-A6add0n** [EXALAB/AnLinux-App#104]
sudo: unable to send audit message              
sudo: pam_open_session: System error
sudo: policy plugin failed session initialization

**Comment by exalab999** [comment]
Could you please post a screenshots about how this error occurred?

**Comment by Th3-A6add0n** [comment]
> Could you please post a screenshots about how this error occurred?

![Screenshot_Termux_20190514-211427](https://user-images.githubusercontent.com/34588916/57712026-84ae6a00-768d-11e9-9d18-fc374853ee70.png)
![Screenshot_Termux_20190514-211350](https://user-images.githubusercontent.com/34588916/57712028-85470080-768d-11e9-86fe-2e4e4ff8fa78.png)

**Comment by Th3-A6add0n** [comment]
> Could you please post a screenshots about how this error occurred?

Before, it was showing me the error I wrote (op)
Now it's showing me 👇
![_20190514_211751](https://user-images.githubusercontent.com/34588916/57712268-e1aa2000-768d-11e9-94b6-9ff60dffb3bb.JPG)

**Comment by farvardin** [comment]
you're already root (~#), no need to use sudo...
