### ISSUE TITLE
Kali NetHunter installation script.

### ISSUE THREAD

**Issue by SnwMds** [EXALAB/AnLinux-App#108]
Please, consider updating the [Kali NetHunter installation script](https://github.com/EXALAB/AnLinux-Resources/blob/master/Scripts/Installer/Nethunter/nethunter.sh) so that it download the latest build. [20190228](https://build.nethunter.com/kalifs/kalifs-20190228).

**Comment by exalab999** [comment]
Yea, sure, I don't know Nethunter update still active and doesn't pay much attention, thanks for remind me! It has been updated
