### ISSUE TITLE
Why not just contribute your efforts to UserLAnd?

### ISSUE THREAD

**Issue by corbinlc** [EXALAB/AnLinux-App#109]
It does the same thing but better and without the outside dependency.

**Comment by corbinlc** [comment]
You have some nice UX/UI features though, except the ads.

**Comment by exalab999** [comment]
Actually there is an adfree version, https://github.com/EXALAB/AnLinux-Adfree. The ads can be annoying sometimes, but unfortunately we need income to maintain this project...
