### ISSUE TITLE
debian+xfce4 - cannot launch browser

### ISSUE THREAD

**Issue by tddschn** [EXALAB/AnLinux-App#111]
## env
distro: debian
DE: xfce4
Android version: 8.0
Anlinux app downloaded from: Google Play Store
Used with: Termux & VNC Viewer (Play Store)
## Error message: 
![image](https://user-images.githubusercontent.com/45612704/58335929-44ad6b00-7e75-11e9-99a4-0fc5015e8df4.png)

failed to execute default web browser

what should I do? thanks in advance!!

**Comment by exalab999** [comment]
Currently default browser not work, please use Firefox or Firefox ESR instead.

**Comment by tddschn** [comment]
thank u, but it seems that I cannot install Firefox using apt or apt-get.

**Comment by exalab999** [comment]
try this: apt install firefox-esr

**Comment by donchris1** [comment]
I installed Firefox and this is the error message I got 
![Screenshot_2019-06-07-21-22-17](https://user-images.githubusercontent.com/43075706/59131642-d1265600-896a-11e9-9e6b-c03e0193557d.png)
By the way, I have tried installing firefox-esr but it said the package is either absolute or not available

**Comment by exalab999** [comment]
In this case how about trying to download Firefox on official website?

**Comment by donchris1** [comment]
How, the browser is not working.

**Comment by bpsib** [comment]
I also got the above error when trying to install firefox-esr. It's because you need to add the Firefox PPA repository. It can be done using the following commands:

`apt-get install software-properties-common`
`add-apt-repository ppa:mozillateam/ppa`

Then try again using `apt-get install firefox-esr`

**Comment by supersonictw** [comment]
Firefox(>=55.0.1) has had some bug on armhf device.
We are sorry that can`t help it if you has the problem,too.

Maybe you can follow the topic.
https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1711337

or Please use Chromium, thank you ;)

**Comment by supersonictw** [comment]
> Firefox(>=55.0.1) has had some bug on armhf device.
> We are sorry that can`t help it if you has the problem,too.
> 
> Maybe you can follow the topic.
> https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1711337
> 
> or Please use Chromium, thank you ;)

If Chromium couldn`t help you resolve the problem.
Try Midori https://www.midori-browser.org/
