### ISSUE TITLE
IT isn't work on xiaomi Redmi 6

### ISSUE THREAD

**Issue by dusan-till** [EXALAB/AnLinux-App#113]

**Comment by exalab999** [comment]
Try the Patch 2 in AnLinux and and then reopen Termux and try again, if it
still not works please post screenshots.

**Comment by dusan-till** [comment]
It's says proot info: vpid 1: terminated with signal 11

**Comment by exalab999** [comment]
The only way to solve this is Patch 2

**Comment by dusan-till** [comment]
I don't know what Is Patch 2

**Comment by exalab999** [comment]
Open the AnLinux, open the drawer on left, click the Patches feature,
choose the second patches and follow the steps.

**Comment by dusan-till** [comment]
Thank you now it's work

**Comment by dusan-till** [comment]
It isn't work again. It's say bash: [: : integer expression expected

**Comment by exalab999** [comment]
please post screenshots about the error

**Comment by dusan-till** [comment]
https://drive.google.com/file/d/1vOXWyQqXPkXEnvRxWr5eDXgdB7gVSkfR/view?usp=drivesdk

**Comment by exalab999** [comment]
I run a test and did not found the error.

You could try to reinstall Termux, then install the patch 2, then reinstall the distro, this should solve the issue.
