### ISSUE TITLE
Official rootfs download links?

### ISSUE THREAD

**Issue by HemanthJabalpuri** [EXALAB/AnLinux-App#115]
I use ubuntu from https://wiki.ubuntu.com/Base ....
But rootfs of [offical](http://cdimage.ubuntu.com/ubuntu-base/releases/19.04/release/ubuntu-base-19.04-base-armhf.tar.gz) one and [yours](https://github.com/EXALAB/AnLinux-Resources/blob/master/Rootfs/Ubuntu/armhf/ubuntu-rootfs-armhf.tar.gz?raw=true) are different why?

**Comment by exalab999** [comment]
My rootfs are built by myself, which contain better optimization for use on
Android, you could find the scripts to build Ubuntu here:
https://github.com/EXALAB/AnLinux-Resources/blob/master/Scripts/Bootstrap/Ubuntu/bootstrap.sh

**Comment by HemanthJabalpuri** [comment]
@exalab999 
Can you please add above answer to README or wiki in more detail, so that someone like me see there.

Also ubuntu is still 18.04 with latest rootfs :- screenshot attached
[Screenshot_20190609-063950](https://user-images.githubusercontent.com/39197123/59153844-c7434680-8a81-11e9-988e-3e21ebd147a4.png)

**Comment by exalab999** [comment]
It is already stated here: https://github.com/EXALAB/AnLinux-Resources

and in the first line of README in AnLinux-App:

This is repo for the main application. If you are looking for the images
and scripts used in this app, please visit here.

I believe this is very clear.


Also, the latest release is Bionic, which is 18.04, is there any problem
with this?

**Comment by HemanthJabalpuri** [comment]
@exalab999
Are these are fine for backing up the distro(ubuntu)?
```
cd ~
tar -xpf /sdcard/ubuntu.tar start-ubuntu.sh ubuntu-binds ubuntu-fs
xz -ze /sdcard/ubuntu.tar
```

and decompressing that backed up archive with
```
cd ~
tar -xJf /sdcard/ubuntu.tar.xz
```

Any permission changes or linking options are required for tar and untar?
