### ISSUE TITLE
Why Input/Output Error occurs when launching browser [[QUESTION]]

### ISSUE THREAD

**Issue by moliata** [EXALAB/AnLinux-App#120]
Hello,
What is the reason behind Input/Output Error which occurs when launching the browser? Is there a missing package, Android security limitation (like SECCOMP) or just generally another problem?
If you could specify the exact problem, it would be great, thanks!
Best regards,
Ben.

**Comment by bpsib** [comment]
I also had this problem at first. I fixed it by installing Firefox using the following commands:

`apt-get install software-properties-common`
`add-apt-repository ppa:mozillateam/ppa`
`apt-get install firefox-esr`

**Comment by moliata** [comment]
@bpsib this is not a question on how to fix the problem, but a question why it happens. Thanks anyways.

**Comment by bpsib** [comment]
I think it happens because XFCE doesn't always have a web browser installed by default. I also got the same or similar error when I first installed Xfce4 on my server if I recall correctly.

**Comment by moliata** [comment]
@bpsib it seems so, after doing `apt-get install firefox`, the issue seems to be gone. It also could be, because of the boostrapping script, I'll take a look at that in the mean while...
