### ISSUE TITLE
Error repo

### ISSUE THREAD

**Issue by DannyKurniawan642** [EXALAB/AnLinux-App#127]
Err:1 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF

Error in Nethunter please how to fix :(

**Comment by exalab999** [comment]
Try using nano in Termux to delete that line, basically that file causeing this error is /etc/apt/sources.list , or file inside directory /etc/apt/sources.list.d/
