### ISSUE TITLE
Keyboard layouts in VNC

### ISSUE THREAD

**Issue by anony11** [EXALAB/AnLinux-App#129]
I'm not very expert on Linux, and it's probably not your fault but:
In the lxde DE and UBUNTU the keyboard is unusable(pressing < outputs 1 and })
In xfce characters aren't triggered(# or @)

The second one could be a VNC client issue, but the first it's probably not.

Regards!

**Comment by supersonictw** [comment]
Could you re-execute the Desktop Install Command like
`wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/LXDE/de-apt-lxde.sh && bash de-apt-lxde.sh`

And try the VNC Client
[RealVNC Viewer](https://play.google.com/store/apps/details?id=com.realvnc.viewer.android)

If it still has any question, report your Linux distribution, Android version and device model.
Thank you. ;)

**Comment by anony11** [comment]
Well, it works, kind of:
Ubuntu, the one you provide(should be updated to the lastest)
Andoird P
Galaxy Note

I think it's a problem of the VNC App, cause, commeting this with keyboard works.
On LXDE while it works, some stuff doesn't like {}[].

**Comment by anony11** [comment]
Since you maintain this repo, should be optimal you ask xsdl(an x server made in sdl) maintainer to update his app to comply to the android policy(app continuously restarts)
