### ISSUE TITLE
COMPATIBILITY WITH SAMSUNG GALAXY A7

### ISSUE THREAD

**Issue by 0ph3li4** [EXALAB/AnLinux-App#130]
Hello everyone!
I'm super satisfied with your app, it's amazing to run Kali/Parrot on an Android phone without root access, but I have a small issue, I'm soon gonna buy a Samsung Galaxy A7, and I'd like to do the same procedure on that phone and get the full access to Kali and its tools, is this app compatible with the A7, please ?
If yes, how can I run the DE version of Kali, please?
Thank you!

**Comment by exalab999** [comment]
Usually all AnLinux script is compatible with Samsung device, to install DE on Kali, first install Kali from Dashboard, then install DE using the Desktop Environment feature.
