### ISSUE TITLE
change locate

### ISSUE THREAD

**Issue by Zel9278** [EXALAB/AnLinux-App#131]
I want to change the language to Japanese, but I get this error
(Fedora 30)
``
[root@localhost ~]# localectl set-locale LANG=ja_JP.UTF-8
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down``

**Comment by exalab999** [comment]
These Linux system does not boot with systemd, so localectl will not work, try using `update-locale` instead, and if still not works, manually change them in the file:

/etc/default/locale – on Ubuntu/Debian
/etc/locale.conf – on CentOS/RHEL

**Comment by Zel9278** [comment]
> These Linux system does not boot with systemd, so localectl will not work, try using `update-locale` instead, and if still not works, manually change them in the file:
> 
> /etc/default/locale – on Ubuntu/Debian
> /etc/locale.conf – on CentOS/RHEL

Thank you, I have one more problem and I get this error if I install Ubuntu and then try to start vncserver again.
``root@localhost:~# vncserver
vncserver: The USER environment variable is not set.``

**Comment by exalab999** [comment]
As you could see in the [vncserver-start](https://github.com/EXALAB/AnLinux-Resources/blob/master/Scripts/DesktopEnvironment/Apt/Xfce4/vncserver-start) file:

Those export command is the way to fix this error, you could run these command one by one every time you start the VNC Server, or better, use the `vncserver-start` command directly. 

If vncserver-start command return command not found error, please use the Desktop Environment feature in AnLinux app.

**Comment by Zel9278** [comment]
> As you could see in the [vncserver-start](https://github.com/EXALAB/AnLinux-Resources/blob/master/Scripts/DesktopEnvironment/Apt/Xfce4/vncserver-start) file:
> 
> Those export command is the way to fix this error, you could run these command one by one every time you start the VNC Server, or better, use the `vncserver-start` command directly.
> 
> If vncserver-start command return command not found error, please use the Desktop Environment feature in AnLinux app.

Okay, let me know the path of that vncserver-start.

**Comment by exalab999** [comment]
Its at `/usr/local/bin`

**Comment by Zel9278** [comment]
> /usr/local/bin

Thank you!!!!
