### ISSUE TITLE
Can't update or install on ParrotOS

### ISSUE THREAD

**Issue by Araly** [EXALAB/AnLinux-App#132]
ParrotOS normally comes with `parrot-upgrade`, but the command isn't installed by default. So you normally can do `apt update` then `apt full-upgrade` but when running update, it complains about the repository codename changing from "stable" to "rolling". It asks whether to change that or not. If you reply no, it will halt. If you reply yes, it will do so, and then complain again.

`W: Conflicting distribution: http://ba.mirror.garr.it/mirrors/parrot stable InRelease (expected stable but got rolling)`

From there, I can't install, update or upgrade anything. Debian and kali work well.

Otherwise, this is an amazing app, love it

**Comment by root1533** [comment]
Eu também estou com mesmo erro

**Comment by exalab999** [comment]
This issue has been fixed recently, it occur because maintainers suddenly decide to change stable to rolling.
