### ISSUE TITLE
An issue with firefox on ubuntu. Am I missing something?

### ISSUE THREAD

**Issue by AA16-Special-Edition** [EXALAB/AnLinux-App#135]
Configured the basics and this happened. What should I do?
Device: SM-J610F
Android version: 9.0 (One UI)
![Screenshot_20190730-202241_VNC Viewer](https://user-images.githubusercontent.com/49526406/62141541-5cd4b700-b30a-11e9-80de-8401576638c3.jpg)

**Comment by supersonictw** [comment]
- same problem https://github.com/EXALAB/AnLinux-App/issues/111

Firefox(>=55.0.1) has had some bug on armhf device.
We are sorry that can`t help it if you has the problem,too.

Maybe you can follow the topic.
https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1711337

or Please use Chromium, thank you ;)

**Comment by AA16-Special-Edition** [comment]
@supersonictw mate here's the thing, chromium crashes too xD

**Comment by AA16-Special-Edition** [comment]
It has something to do with ubuntu itself (?) ig cuz epiphany had the same issue. Then I installed arora, 1st time running: gibberish input. 2nd time running: Same issue as those two before. The interesting thing is I can still interact with where the elements should be but they just don't render. Here's what I'm using now lol, went full amoled
![Screenshot_20190803-162320_VNC Viewer](https://user-images.githubusercontent.com/49526406/62411025-960f6e80-b60b-11e9-900b-158ea15de8d8.jpg)

**Comment by supersonictw** [comment]
How about Midori ?
https://www.midori-browser.org/

**Comment by AA16-Special-Edition** [comment]
@supersonictw :/
![Screenshot_20190803-180638_VNC Viewer](https://user-images.githubusercontent.com/49526406/62412012-9d3d7900-b619-11e9-9555-09699af4ef49.jpg)
![Screenshot_20190803-180329_VNC Viewer](https://user-images.githubusercontent.com/49526406/62412013-9dd60f80-b619-11e9-8f4b-3404fa1abbae.jpg)

**Comment by supersonictw** [comment]
We are sorry that we can not solve the problem by these browser.
Please try the one [AnLinux-Browser](https://github.com/star-inc/AnLinux-Browser.git) that will help you to visit some simple pages.
We will find more solution, thank you.

**Comment by AA16-Special-Edition** [comment]
Lol. Anyways backed up the fs and commited delet of termux cuz I needed that space. WHAT IS THAT PFP THO @supersonictw

**Comment by supersonictw** [comment]
Yaesakura
