### ISSUE TITLE
can't sanitize binding "ubuntu-fs/root": No such file or directory

### ISSUE THREAD

**Issue by Cpt-Squirrell** [EXALAB/AnLinux-App#138]
Sincere apology if this is dumb. I am new to the Linux universe. My friend has talked me into it.

`./start-ubuntu.sh
proot warning: can't sanitize binding "ubuntu-fs/root": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.`

**Comment by exalab999** [comment]
Try to reinstall Termux may fix this problem
