### ISSUE TITLE
Desktop Environment Support

### ISSUE THREAD

**Issue by exalab999** [EXALAB/AnLinux-App#14]
If you have any tweak or suggestion about Desktop Environment, please post it below.

Currently Supported Distro:

All distro except CentOS and openSUSE, Arch Linux only works with LXDE.

Testing List:

-

Blacklisted (Will not be tested):

1. [Gnome](https://www.gnome.org/)
2. [KDE](https://www.kde.org/)
3. [Cinnamon](https://cinnamon-spices.linuxmint.com/)

**Comment by Efreak** [comment]
Suggestion: IceWM. Primarily due to small install size.

**Comment by exalab999** [comment]
@Efreak Thanks for the suggestion, we will consider it.

**Comment by hyiltiz** [comment]
And i3wm

**Comment by sarthak247** [comment]
@exalab999 why have GNOME and KDE been blacklisted? Also, is it possible to add support for Deepin DE for Arch Linux

**Comment by supersonictw** [comment]
@sarthak247 Because of the "systemd" couldn`t run in chroot(proot) mode...but it`s required.

**Comment by sid5687526** [comment]
I m surfing with this problem while going for desktop view 

- 
![Screenshot_20190817-145904_Chrome](https://user-images.githubusercontent.com/54204555/63209543-f3bdb380-c0ff-11e9-994d-9999c9d874e2.jpg)

**Comment by sid5687526** [comment]
> please solve my ptoblem for installing kali linux in desktop view
![Screenshot_20190817-145904_Chrome](https://user-images.githubusercontent.com/54204555/63209621-d89f7380-c100-11e9-8fa9-77559d0d4df4.jpg)

**Comment by supersonictw** [comment]
@sid5687526 
Try re-execute the "Desktop Install Command":

    wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/de-apt-xfce4.sh && bash de-apt-xfce4.sh

**Comment by sid5687526** [comment]
![Screenshot_20190818-164215_Termux](https://user-images.githubusercontent.com/54204555/63223702-a6ad1080-c1d7-11e9-8528-5653368d1c5a.jpg)
![Screenshot_20190818-164218_Termux](https://user-images.githubusercontent.com/54204555/63223703-a6ad1080-c1d7-11e9-90d7-2613ab52740a.jpg)
![Screenshot_20190818-164009_Termux](https://user-images.githubusercontent.com/54204555/63223704-a745a700-c1d7-11e9-834d-557f755a6303.jpg)
![Screenshot_20190818-164220_Termux](https://user-images.githubusercontent.com/54204555/63223705-a745a700-c1d7-11e9-9b36-c205d531057e.jpg)
![Screenshot_20190818-164016_Termux](https://user-images.githubusercontent.com/54204555/63223706-a7de3d80-c1d7-11e9-9637-6599f08cc557.jpg)
![Screenshot_20190818-164222_Termux](https://user-images.githubusercontent.com/54204555/63223707-a876d400-c1d7-11e9-9e99-32381be9126e.jpg)
![Screenshot_20190818-164026_Termux](https://user-images.githubusercontent.com/54204555/63223708-a9a80100-c1d7-11e9-8d4c-1d030183befe.jpg)
![Screenshot_20190818-164224_Termux](https://user-images.githubusercontent.com/54204555/63223709-ab71c480-c1d7-11e9-83f8-8023f6d40c1a.jpg)
![Screenshot_20190818-164031_Termux](https://user-images.githubusercontent.com/54204555/63223710-ac0a5b00-c1d7-11e9-98ff-7af32597ecf8.jpg)
![Screenshot_20190818-164226_Termux](https://user-images.githubusercontent.com/54204555/63223711-ac0a5b00-c1d7-11e9-9a4c-1fa6878e3e41.jpg)
![Screenshot_20190818-164045_Termux](https://user-images.githubusercontent.com/54204555/63223712-add41e80-c1d7-11e9-99dd-cbf0b75f3dbe.jpg)
![Screenshot_20190818-164227_Termux](https://user-images.githubusercontent.com/54204555/63223714-af054b80-c1d7-11e9-948c-1c96507685cc.jpg)
![Screenshot_20190818-164052_Termux](https://user-images.githubusercontent.com/54204555/63223715-b167a580-c1d7-11e9-923f-d1f9788f5046.jpg)
![Screenshot_20190818-164251_Termux](https://user-images.githubusercontent.com/54204555/63223716-b167a580-c1d7-11e9-88e8-5be0c5a7f580.jpg)
![Screenshot_20190818-164057_Termux](https://user-images.githubusercontent.com/54204555/63223717-b3316900-c1d7-11e9-8622-71050f8d7c6e.jpg)
![Screenshot_20190818-164107_Termux](https://user-images.githubusercontent.com/54204555/63223718-b6c4f000-c1d7-11e9-98cc-320984275776.jpg)
![Uploading Screenshot_20190818-164116_Termux.jpg…]()
![Uploading Screenshot_20190818-164122_Termux.jpg…]()
![Uploading Screenshot_20190818-161644_Termux.jpg…]()
![Uploading Screenshot_20190818-164129_Termux.jpg…]()
![Uploading Screenshot_20190818-164132_Termux.jpg…]()
![Uploading Screenshot_20190818-164136_Termux.jpg…]()
![Uploading Screenshot_20190818-164143_Termux.jpg…]()
![Uploading Screenshot_20190818-164159_Termux.jpg…]()
![Uploading Screenshot_20190818-164202_Termux.jpg…]()
![Uploading Screenshot_20190818-164205_Termux.jpg…]()
![Uploading Screenshot_20190818-164208_Termux.jpg…]()
![Uploading Screenshot_20190818-164210_Termux.jpg…]()
![Uploading Screenshot_20190818-164212_Termux.jpg…]()

**Comment by sid5687526** [comment]
same oUtput was coming

**Comment by Kilo-411** [comment]
That's most likely got something to do with the vnc your running, of course I not 100% sure I'm just replying cause I see this was 21 days ago. I would check if I knew what vnc I run the same desktop on one of my phones I'm sure..

**Comment by Mei-Giyanto22** [comment]
Are there other alternatives besides tigerVNC according to the guidelines of the AnLinux application?
because I did not find the intended application in Playstore

I experienced the same thing, which was error
"line 4: command not found"

**Comment by aidlearning** [comment]
Another solution of termux desktop environment....[AidLearning Framework](https://github.com/aidlearning/AidLearning-FrameWork)

**Comment by bruh-droid** [comment]
I tested kde it is works (lagged)

**Comment by hyiltiz** [comment]
@bruh-droid can you describe you how did it, where you needed to hack around?

**Comment by DannyKurniawan642** [comment]
Kde it work debian 9/10

**Comment by LuckyStar04** [comment]
how to run vncserver as a user(not root)?
I have installed ubuntu, xfce4, vncserver runs good as root
but when I try it as a normal user, i got this
![Screenshot_20200222-175325](https://user-images.githubusercontent.com/12585755/75090336-c8c78700-559c-11ea-860d-41ea48288510.png)

**Comment by 0xc0000007b** [comment]
> Another solution of termux desktop environment....[AidLearning Framework](https://github.com/aidlearning/AidLearning-FrameWork) don't need vnc and x11....

Thank you so very much for spamming us with self-serving, off-topic content.
