### ISSUE TITLE
Parrot

### ISSUE THREAD

**Issue by lakis12345** [EXALAB/AnLinux-App#152]
#apt install git
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package git

#apt update
Hit:1 http://ba.mirror.garr.it/mirrors/parrot stable InRelease
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
W: Conflicting distribution: http://ba.mirror.garr.it/mirrors/parrot stable InRelease (expected stable but got rolling)

Help me

**Comment by exalab999** [comment]
Thanks for reporting this, please edit this file:
parrot-fs/etc/apt/sources.list

And change stable to rolling.

You would need to use file editor in Termux since apt is not working in
Parrot, just restart Termux and run pkg install nano to install the editor.

We will fix this in 3 days so future users will not encounter this error
again.

**Comment by lakis12345** [comment]
Made packages updated but 
#apt install python 
Reading package lists ... 
Done Building dependency tree ... Done 
E: Unable to locate package python3

**Comment by exalab999** [comment]
Follow the solution I provided above then run apt update again.

**Comment by lakis12345** [comment]
I replaced stable with rolling next ./start-parrot.sh apt update Everything But nothing works

**Comment by exalab999** [comment]
I tried just now and worked after changing stable to rolling, this is
weird...

**Comment by lakis12345** [comment]
I do not know what's happening I reinstalled, but all the same ...

**Comment by lakis12345** [comment]
I do not know what's happening I reinstalled, but all the same ...

**Comment by exalab999** [comment]
I will fix it as soon as possible and run a re-test, I will let you know
when it is done.

**Comment by lakis12345** [comment]
I wanted to install xfce with the command 
apt install xfce4 
But with a mistake vncserver: 1 -geometry 700x1400 -dpi 120 vncserver: The USER environment variable is not set. 
Also set through your program but in vnc only half the screen 
I ask for help

**Comment by exalab999** [comment]
Run these command then run the vncserver command again:

export USER=root && export HOME=/root

However it is advised to use the Desktop Environment feature in AnLinux instead, it is automated to do all the complicated things with one click.

**Comment by lakis12345** [comment]
Is the update coming soon?

**Comment by exalab999** [comment]
@lakis12345 Sorry for the delay, actually the fix is implemented some days ago, I am busy working on the new version and forgot about that. Reinstall the Parrot Security OS now should fix the problem.
