### ISSUE TITLE
Parrot Security OS Repo Issue

### ISSUE THREAD

**Issue by exalab999** [EXALAB/AnLinux-App#155]
Currently Parrot Security OS is having a very big issue. Attempt to update the repo using apt update would result in get a 14 kb InRelease file and nothing else. 

This issue will remain here until solved, if you have any solution please provide it so we could fix this problem, thanks.

**Comment by exalab999** [comment]
As additional info, the Packages.gz file for arm is in very small size, not sure if the decided to drop support for arm and arm64:

[https://deb.parrotsec.org/parrot/dists/rolling/main/binary-armhf/](https://deb.parrotsec.org/parrot/dists/rolling/main/binary-armhf/)

**Comment by shinta4ever** [comment]
So this is what is causing the issue of xfce package not being found.

**Comment by Varun-Patkar** [comment]
Has this issue been resolved? I had tried to install Parrot in November and had faced the same problem Wanna retry.

**Comment by GPratyush01** [comment]
i guess no.. but i will suggest you to install ubuntu.. it works best both are same just differense is parrot comes with pre-installed hacking tools and ubuntu comes with no tools .. so you can learn more if you will install an ubuntu in your termux ... good luck

**Comment by GPratyush01** [comment]
https://deb.parrotsec.org/parrot/dists/rolling/main/binary-armhf/ 
the packeg file looks like has been edited this month of january .. so you can try this if you want to ..  but i can't gurantee that it will work ..

**Comment by tinnus1988** [comment]
1

**Comment by exalab999** [comment]
This is now fixed by the devs and Parrot Security OS available on all device again.
