### ISSUE TITLE
amd64 should be x86_64

### ISSUE THREAD

**Issue by ric96** [EXALAB/AnLinux-App#19]
OS: Android 8.1 rc-2 android-x86

On android x86, running Termux. ```dpkg --print-architecture``` returns ```x86_64``` instead of ```amd64```
The script hence fails with ```unknown architecture```
changing amd64 case to x86_64 case in the script makes it run as expected.

**Comment by exalab999** [comment]
Thanks for reporting this bug, it has been fixed just now.
