### ISSUE TITLE
Libreoffice /proc not mounted

### ISSUE THREAD

**Issue by dsvilko** [EXALAB/AnLinux-App#24]
Is there any workaround? Libreoffice fails to start on ubuntu complaining that the /proc is not mounted. It is but I guess on Oreo some virtual files are not accessible.

**Comment by exalab999** [comment]
The start-ubuntu.sh in Termux mount Android local /proc in the distro, you can try to uncomment that line of code to see if it works.

**Comment by dsvilko** [comment]
It doesn't. The problem is not that the /proc filesystem is mounted but that it's not fully mounted. Has anyone got the libreoffice to run through proot on Oreo?

**Comment by sujitvasanth** [comment]
Hi I had the same problem when trying to install open office on ubuntu mate running on an oreo based phone.
I switched to kali linux on Android 6.0 and works fine.
the problem is access permission on Android 8 and above.

**Comment by serovar** [comment]
[Issue solvable either via `setenforce 0` or running program under "tsu". Both variants require device to be rooted.](https://github.com/termux/termux-app/issues/299).

For me setting SELinux mode to Permissive via `setenforce 0` on Termux (after gaining root permission in a rooted device through `su`) did the trick.

**Comment by DarthZedd** [comment]
Is there any other option except rooting the device?

**Comment by Zin-Uru** [comment]
I've found a way. You can edit file /usr/lib/libreoffice/program/oosplash with any HEX editor (bless for example). Just find text "/proc/version" (LibreOffice checks this file) and change to for example "/prod/version". Then you can create fake empty "/prod/version" file in the filesystem, then Office starts and works well (source code says /proc is very important but I can't find any issue, maybe because /proc partially accessible since it is "mounted" with proot to the guest system).
Not very fine method but now is yhe only one without root.

**Comment by frpe98** [comment]
Zin-Uru's solution worked awesome for me on Andronix Modded Ubuntu version. Thanks so much!

**Comment by yununusmulla** [comment]
Zin-Uru.. sir i have tried this method but it says something like permission denied please help sir here is screenshOt
![Screenshot_20200710-115059_VNC Viewer](https://user-images.githubusercontent.com/68098793/87123056-aa3fff00-c2a3-11ea-9f65-1c9fb22f1253.jpg)

**Comment by yununusmulla** [comment]
![Screenshot_20200710-115059_VNC Viewer](https://user-images.githubusercontent.com/68098793/87123108-c2b01980-c2a3-11ea-8c26-3cdc54da112f.jpg)

**Comment by khenty** [comment]
Or just edit  /usr/lib/libreoffice/program/oosplash with emacs, then create /prod/version. What a hack! Thanks, Zin-Uru.

**Comment by infinyte7** [comment]
I have created a python script [fix-libreoffice.py](https://github.com/infinyte7/manjaro-fs-arm64/blob/main/scripts/fix-libreoffice.py) to automate this process for Arch base distro.

Copy and run in Arch based distro
```
wget https://raw.githubusercontent.com/infinyte7/manjaro-fs-arm64/main/scripts/fix-libreoffice.py && python fix-libreoffice.py
```

**Comment by freebrowser1** [comment]
Four years later... this patch works in Andronix on a non-rooted Android !

**Comment by mrmaking** [comment]
Works on Debian/xfce from andronix.  Thanks, libreoffice is what tablet most needed.
