### ISSUE TITLE
KDE for Ubuntu

### ISSUE THREAD

**Issue by exalab999** [EXALAB/AnLinux-App#252]
Many users are asking us for KDE for Ubuntu, we did make it possible with some scripts, which is available here: [KDE for Ubuntu](https://github.com/EXALAB/Anlinux-Resources/tree/master/Scripts/DesktopEnvironment/Heavy/KDE/Ubuntu)

This script work correctly on Ubuntu 18 (Bionic), but is does not work anymore since Ubuntu 20 (Focal), if you know how to fix this problem please feel free to contribute.

For anyone that contribute a working fix to this script, their name will be mentioned in the Heavy DE Page and in the script.

This issue has been solved for now, but still open for further discussion. The tag has been removed for now, but might re-add in case KDE conflict with the new Ubuntu release.

**Comment by Michelle99798** [comment]
@michelle

**Comment by Michelle99798** [comment]
@Michelle99798

**Comment by hghhuy** [comment]
termux

**Comment by hghhuy** [comment]
#56

**Comment by hghhuy** [comment]
termux

**Comment by hghhuy** [comment]
@supersonictw

**Comment by hghhuy** [comment]
Android

**Comment by hghhuy** [comment]
ubuntu

**Comment by hghhuy** [comment]
ubuntu

**Comment by hghhuy** [comment]
ubuntu.sh

**Comment by ultrahacx** [comment]
Android and Linux SELinux policies conflict each other, also multiple unknow PRoot limitations cause issue. There's no way around to get KDE or other mainstream DE such as GNOME working on latest linux builds/latest Android version.

**Comment by RiNaT059-TaT** [comment]
ubuntu.sh

**Comment by RiNaT059-TaT** [comment]
termux

**Comment by SaiLoanKhum** [comment]
No Display inFocal

**Comment by RiNaT059-TaT** [comment]
Setop display

**Comment by RiNaT059-TaT** [comment]
Setup display

**Comment by daleleslie** [comment]
What to do

**Comment by daleleslie** [comment]
What the hell

**Comment by akshay445** [comment]
As of now ubuntu kde 20.04 will not work on latest builds of android. however it would be great if the developer could add the option to install ubuntu kde 18.04

**Comment by TaTaRsKiY059** [comment]
Update

**Comment by sarisarina** [comment]
😊

**Comment by 3vau** [comment]
When I tried to install KDE or Gnome with package manager on my Linux in termux, I met a problem that they must run with systemd. Maybe someone can try it with tsu? or if there are some ways to simulate systemd in termux?...

**Comment by georgell2** [comment]
wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/de-apt-xfce4.sh && bash de-apt-xfce4.sh

**Comment by 935088** [comment]
Nice

**Comment by Youssef2351** [comment]
pacman -Sy --noconfirm wget && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Pacman/de-pac.sh && bash de-pac.sh

**Comment by Hassan92Wa** [comment]
wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/de-apt-xfce4.sh && bash de-apt-xfce4.sh

**Comment by Moooebie** [comment]
Hello. I tried the script on Focal, the result is it throws an error message like "startkde: Could not start kdeinit5", and the log shows "/usr/bin/kdeinit5: Permission denied" (while there shouldn't be a permission problem). 
Is this issue about this problem? Or that's because of I did something else wrongly?

**Comment by 3vau** [comment]
> Hello. I tried the script on Focal, the result is it throws an error message like "startkde: Could not start kdeinit5", and the log shows "/usr/bin/kdeinit5: Permission denied" (while there shouldn't be a permission problem). 
> Is this exactly the reason you posted this issue? Or that's because of I did something else wrongly?

emmm the problem may happened on prefix...if the package is insalling to the correct place - $PREFIX, the path will be "/data/data/com.termux...", but not "/usr"... I think you musn't use tsu, or you may have a Android with KDE‍😛
Override the install script may solve the problem?~

**Comment by maalos** [comment]
EUREKA!!! Got KDE to work on 20.04! The error was with fprintd, libfprint-2-2 wasn't configured, and when configuring it threw errors at me. The sollution was to remove a few postinst files. The command i used after running the installation script was:
```
rm /var/lib/dpkg/info/fprintd.postinst
rm /var/lib/dpkg/info/libfprint-2-2*.postinst
rm /var/lib/dpkg/info/libpam-fprintd*.postinst
dpkg --configure -a
```

**Comment by maalos** [comment]
@exalab999 i don't know if that is the error you're having but i definitely fixed mine. I'd be cool if you gave details on what failed in the script, and maybe some steps to reproduce.

**Comment by Wrench45** [comment]
👍

**Comment by exalab999** [comment]
@maalos With those command KDE start to work again on Ubuntu Focal, I could even run Firefox fully on it, while the reason is not known, I will update the app and script so all users could use KDE, your name will be mentioned in the script, thank you very much for the help!

**Comment by maalos** [comment]
LMAO i thought that was going to fix it only for me, surely didn't expect that to happen, but well, guess i did it

**Comment by maalos** [comment]
though i still have some issues, and can't start the X server. my problem is that `libkdeinit5_kded5` is required by `kded5`, and it's missing, so it ends up crashing right after it gets opened.
