### ISSUE TITLE
how to use the vnc server

### ISSUE THREAD

**Issue by adbenitez** [EXALAB/AnLinux-App#26]
sorry the dummy question but never worked with vnc servers before,
I had follow the instructions in the apk to install Debian, after that I had follow the instructions to install the Desktop Environment, but after ``de-apt.sh`` script  ends I don't know what to do, I see the message that I can use "the VNC Viewer you prefer" but no one is suggested as example and an example of how to execute one with parameters, would be nice.
I had installed ``tigervnc-viewer`` and  when I run ``vncviewer 127.0.0.1:5901`` the program prints some messages as it is working normally but it hangs and don't ask me for passwords, nothing s displayed just the terminal waiting.
please help!

**Comment by adbenitez** [comment]
UPDATE: I now issued the command ``vncviewer --passwd=.vnc/passwd localhost:1`` and it goes further but still hangs at some point, the ``.vnc/localhost:1.log`` file say some messages about ignoring unknow encoding ex.:
``rfbProcessClientNormalMessage: ignoring unknow encoding -223``

**Comment by exalab999** [comment]
Simply run `vncserver-start` to start the vncserver, it is located at /usr/local/bin.

After that connect to 127.0.0.1:5901 with VNC Viewer, we recommend this: [VNC Viewer - Remote Desktop](https://play.google.com/store/apps/details?id=com.realvnc.viewer.android&hl=en)

**Comment by adbenitez** [comment]
I don't use google play, and also your suggested apk don't seems to be free(as in freedom) :P 
I will try the ones on f-droid.
Anyway thanks for pointing out that it is an apk and not a package inside the Debian environment.
Regards,
adb

**Comment by YonahYudha1997** [comment]
Help me that how can access internet in my Kali vnc
