### ISSUE TITLE
Error while opening kali on vnc

### ISSUE THREAD

**Issue by bubbelbadHD** [EXALAB/AnLinux-App#280]
After so many hours I finally managed to get kali linux on vnc but when I start it, it gives an error
"Unable to execute child process"
And the background screen is all static. Please please help me
![Screenshot_2021-01-19-21-41-42-462_com realvnc viewer android](https://user-images.githubusercontent.com/77578305/105061107-2317e300-5a9f-11eb-8495-0f3b5a08b9f6.png)

**Comment by douglascarlini** [comment]
Same problem here
![Uploading Screenshot_2021-01-20-00-35-43-86_8659c1e795b4b4239e38d87c88c077b3.jpg…]()

**Comment by douglascarlini** [comment]
apt install dbus-x11

**Comment by bubbelbadHD** [comment]
Should I put it before entering all the commands or at the end?

**Comment by douglascarlini** [comment]
Inside distro, after `./start-kali.sh`

**Comment by bubbelbadHD** [comment]
Ok thanks

**Comment by bubbelbadHD** [comment]
It show this error
![Uploading Screenshot_2021-01-20-10-28-08-917_com.termux.png…]()

**Comment by bubbelbadHD** [comment]
![Screenshot_2021-01-20-10-28-08-917_com termux](https://user-images.githubusercontent.com/77578305/105129086-52b00500-5b0a-11eb-9a7c-63b9ad385a6d.png)

**Comment by bubbelbadHD** [comment]
It shows an error

**Comment by bubbelbadHD** [comment]
I used the windows manager as mate and it worked!
![Screenshot_2021-01-20-11-28-26-401_com realvnc viewer android](https://user-images.githubusercontent.com/77578305/105133359-a1fa3380-5b12-11eb-9e1e-24e1912844ed.png)

**Comment by bubbelbadHD** [comment]
Thankyou
