### ISSUE TITLE
groups err

### ISSUE THREAD

**Issue by chytrik** [EXALAB/AnLinux-App#3]
Hi all.
I run the install and it ends like that:
   `$ ./start-ubuntu.sh`
   `groups: cannot find name for group ID 3003`
   `groups: cannot find name for group ID 9997`
   `groups: cannot find name for group ID 50080`
   `root@localhost:~#`
Is it OK?

Then, I couldn't add a user
   `root@localhost:~# adduser john`
   `Adding user john ...`
   `Adding new group john (1000) ...`
   `Cannot open audit interface - aborting.`
   `adduser: /usr/sbin/groupadd -g 1000 john returned error code 1. Exiting.`
   `root@localhost:~#`

`

Thanks.

Best Regards
- Patrik Acer Chromebook 14 for Work (lars)

**Comment by chytrik** [comment]
comment: debian works correctly

**Comment by exalab999** [comment]
The error when running ./start-ubuntu.sh is harmless, you can simply igrone them. 

Which system have the  issue unable to add user?

**Comment by smilearric** [comment]
Hello,

I've got the same error on mine:
• OnePlus 5T (ONEPLUS A5010)
• Android 9 (kernel 4.4.153-perf+ #1)
• OxygenOS OP5T_O2_BETA_20
• Build ONEPLUS A5010_43_181205
• disabled GAPPS & Google Play Services

Apps from f-droid:
• Termux v.0.65
• AnLinux v.4.94


Welcome to Termux!

$ pkg install wget proot -y && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh && bash ubuntu.sh
Get:1 https://termux.net stable InRelease [1720 B]
Get:2 https://termux.net stable/main all Packages [5496 B]
Get:3 https://termux.net stable/main aarch64 Packages [65.9 kB]
Fetched 73.1 kB in 1s (70.7 kB/s)
Reading package lists... Done
Building dependency tree... Done
8 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  libtalloc libunistring libuuid pcre2
The following NEW packages will be installed:
  libtalloc libunistring libuuid pcre2 proot wget
0 upgraded, 6 newly installed, 0 to remove and 8 not upgraded.
Need to get 867 kB of archives.
After this operation, 3748 kB of additional disk space will be used.
Get:1 https://termux.net stable/main aarch64 libtalloc aarch64 2.1.14 [9660 B]
Get:2 https://termux.net stable/main aarch64 libunistring aarch64 0.9.10 [366 kB]
Get:3 https://termux.net stable/main aarch64 libuuid aarch64 1.0.3-2 [4416 B]
Get:4 https://termux.net stable/main aarch64 pcre2 aarch64 10.32 [235 kB]
Get:5 https://termux.net stable/main aarch64 proot aarch64 5.1.107-18 [60.0 kB]
Get:6 https://termux.net stable/main aarch64 wget aarch64 1.20 [192 kB]
Fetched 867 kB in 0s (1984 kB/s)
Selecting previously unselected package libtalloc.
(Reading database ... 416 files and directories currently installed.)
Preparing to unpack .../0-libtalloc_2.1.14_aarch64.deb ...
Unpacking libtalloc (2.1.14) ...
Selecting previously unselected package libunistring.
Preparing to unpack .../1-libunistring_0.9.10_aarch64.deb ...
Unpacking libunistring (0.9.10) ...
Selecting previously unselected package libuuid.
Preparing to unpack .../2-libuuid_1.0.3-2_aarch64.deb ...
Unpacking libuuid (1.0.3-2) ...
Selecting previously unselected package pcre2.
Preparing to unpack .../3-pcre2_10.32_aarch64.deb ...
Unpacking pcre2 (10.32) ...
Selecting previously unselected package proot.
Preparing to unpack .../4-proot_5.1.107-18_aarch64.deb ...
Unpacking proot (5.1.107-18) ...
Selecting previously unselected package wget.
Preparing to unpack .../5-wget_1.20_aarch64.deb ...
Unpacking wget (1.20) ...
Setting up libtalloc (2.1.14) ...
Setting up libunistring (0.9.10) ...
Setting up pcre2 (10.32) ...
Setting up libuuid (1.0.3-2) ...
Setting up proot (5.1.107-18) ...
Setting up wget (1.20) ...
--2018-12-15 13:10:47--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh
Resolving raw.githubusercontent.com... 151.101.36.133
Connecting to raw.githubusercontent.com|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2091 (2.0K) [text/plain]
Saving to: ‘ubuntu.sh’

ubuntu.sh     100%   2.04K  --.-KB/s    in 0.001s

2018-12-15 13:10:48 (3.81 MB/s) - ‘ubuntu.sh’ saved [2091/2091]

Download Rootfs, this may take a while base on your internet speed.
--2018-12-15 13:10:48--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Rootfs/Ubuntu/arm64/ubuntu-rootfs-arm64.tar.gz
Resolving raw.githubusercontent.com... 151.101.36.133
Connecting to raw.githubusercontent.com|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62995584 (60M) [application/octet-stream]
Saving to: ‘ubuntu-rootfs.tar.gz’

ubuntu-rootfs 100%  60.08M  7.69MB/s    in 10s

2018-12-15 13:10:59 (5.84 MB/s) - ‘ubuntu-rootfs.tar.gz’ saved [62995584/62995584]

Decompressing Rootfs, please be patient.


writing launch script
fixing shebang of start-ubuntu.sh
making start-ubuntu.sh executable
removing image for some space
You can now launch Ubuntu with the ./start-ubuntu.sh script

$ pwd
/data/data/com.termux/files/home

$ ls
start-ubuntu.sh  ubuntu-fs
ubuntu-binds     ubuntu.sh

$ ./start-ubuntu.sh
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 20091
groups: cannot find name for group ID 50091
groups: cannot find name for group ID 99909997

root@localhost:~# groups
root groups: cannot find name for group ID 3003
3003 groups: cannot find name for group ID 9997
9997 groups: cannot find name for group ID 20091
20091 groups: cannot find name for group ID 50091
50091 groups: cannot find name for group ID 99909997
99909997

root@localhost:~#

**Comment by LilyGO** [comment]
@chytrik @smilearric Is your problem solved? I also encountered the same problem.

**Comment by LilyGO** [comment]
I found a solution. This is just a warning and you can ignore it. But if you don't want to display the information, you can edit it like this.
https://askubuntu.com/questions/463349/groups-cannot-find-name-for-group-id

**Comment by exalab999** [comment]
Just to inform, this has been fixed yesterday.

**Comment by yewin123** [comment]
Hi I got this can u fix me 
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/SSH/Apt
