### ISSUE TITLE
proot warning 

### ISSUE THREAD

**Issue by Eslamsk** [EXALAB/AnLinux-App#30]
How i can solve this problem i always face it Cant install any desktop environment bc of this problem it's stopping at: - Building database of manual pages ...

./start-parrot.sh
┌─[root@localhost]─[~]
└──╼ #dpkg --configure -a
Setting up man-db (2.8.4-3) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Building database of manual pages ...
./tracee/event.c:517: int handle_tracee_event(Tracee *, int): assertion "!IS_IN_SYSENTER(tracee)" failed
proot warning: signal 6 received from process 31315
$

**Comment by exalab999** [comment]
Hi,

Try to run this when starting the system:

export PROOT_NO_SECCOMP=1 && ./start_parrot.sh

Please let us know if it is working, thanks :)


Regards, EXA Lab

**Comment by abdotufeq** [comment]
After that try 
apt remove man.db
apt update && apt upgrade 
and proceed
