### ISSUE TITLE
EUREKA!!! Got KDE to install on focal! In my case, the error was with fprintd, libfprint-2-2 wasn't configured, and when configuring it threw errors at me. The sollution was to remove a few postinst files. The command i used after running the installation script was:

### ISSUE THREAD

**Issue by Kornphan** [EXALAB/AnLinux-App#319]
EUREKA!!! Got KDE to install on focal! In my case, the error was with fprintd, libfprint-2-2 wasn't configured, and when configuring it threw errors at me. The sollution was to remove a few postinst files. The command i used after running the installation script was:
```
rm /var/lib/dpkg/info/fprintd.postinst
rm /var/lib/dpkg/info/libfprint-2-2*.postinst
rm /var/lib/dpkg/info/libpam-fprintd*.postinst
dpkg --configure -a
```

_Originally posted by @maalos in https://github.com/EXALAB/AnLinux-App/issues/252#issuecomment-903151228_

**Comment by maalos** [comment]
why tf did u make an issue about your success and not just comment on the original? bruh
