### ISSUE TITLE
Inclusion in F-Droid repo

### ISSUE THREAD

**Issue by renatocan** [EXALAB/AnLinux-App#32]
Hi,

Great app! I think it should be included in [F-Droid](https://f-droid.org/) repo. I can submit it but I need your consent. Is it ok for me to submit the app?

Thanks,

Renato.

**Comment by exalab999** [comment]
Sure, I've just finish creating the ad free version: [AnLinux-Adfree](https://github.com/EXALAB/AnLinux-Adfree), also this thread is a duplicate of [#31](https://github.com/EXALAB/AnLinux-App/issues/31), I will close it now.
