### ISSUE TITLE
vnc打开黑屏

### ISSUE THREAD

**Issue by MQNB** [EXALAB/AnLinux-App#342]
![Screenshot_2021-12-30-10-22-37-47_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/96853042/147717069-e625d09c-eca1-4c8f-8f36-3c9769e4659f.jpg)
vnc打开之后黑屏
Black screen after VNC is turned on
![Screenshot_2021-12-30-10-24-23-19_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/96853042/147717201-dba87e76-6af2-4cf1-9b5f-23b0ca041ce8.jpg)
安装dbus-x11​也不成功
The installation of "dbus-x11" was also unsuccessful

**Comment by supersonictw** [comment]
想請問您所使用的發行版是？
Excuse me, what's the distro you are using?

**Comment by Gingmzmzx** [comment]
我也是同样的问题
I have the same problem

**Comment by dontknowhy** [comment]
> ![Screenshot_2021-12-30-10-22-37-47_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/96853042/147717069-e625d09c-eca1-4c8f-8f36-3c9769e4659f.jpg)
> vnc打开之后黑屏
> Black screen after VNC is turned on
> ![Screenshot_2021-12-30-10-24-23-19_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/96853042/147717201-dba87e76-6af2-4cf1-9b5f-23b0ca041ce8.jpg)
> 安装dbus-x11​也不成功
> The installation of "dbus-x11" was also unsuccessful

暴力解决：apt install 'dbus-*'
要不成就把容器全删了
（设个中文罢（恼））
