### ISSUE TITLE
How to automatically login as a certain user 

### ISSUE THREAD

**Issue by theblobscp** [EXALAB/AnLinux-App#343]
I want to login as a user by default as I use pacstall which doesn't work as root.  I tried editing everything in start-debian.sh that said root but it still didn't work. How can I achieve this?

**Comment by mats1729** [comment]
You may have solved the problem by now, but for reference:
One can effectively login as user user_name by adding two lines to the file /root/.bashrc in debian

su -G sudo -l user_name
exit

The "-G sudo" appears to be necessary if user user_name should be able to sudo. Just adding the user to the sudo group doesn't seem to work.

To login as root, one would then have to use a modified start-debian.sh, with "--norc" added to the bash command.

**Comment by theblobscp** [comment]
Thanks, it worked

**Comment by theblobscp** [comment]
Forgot to close this
