### ISSUE TITLE
Termux style doesn't work for ubuntu

### ISSUE THREAD

**Issue by aariow** [EXALAB/AnLinux-App#347]
Hey,
Termux-style doesn't work perfectly for ubuntu and paths.
![Screenshot_20220215-221536_Termux](https://user-images.githubusercontent.com/39987472/154126382-526d8d65-b413-4845-852f-0f6c9d90d9de.jpg)

What should we do to colorize ubuntu's content ?
Thanks

**Comment by supersonictw** [comment]
Because you're using different shell configure (Termux | Ubuntu).
You can configure your prefer style with your `~/.bashrc`

https://ncurl.xyz/s/-317JYf7g
