### ISSUE TITLE
USB/OTG udisk

### ISSUE THREAD

**Issue by Sugar-paper** [EXALAB/AnLinux-App#357]
how can i rw a udisk or sdcard from otg？
in termux can find at: /mnt/media_rw/

but after run
tus
./start-ubuntu.sh

then run
mount /dev/block/by-name/userdata /mnt
I can't find media_rw in /mnt

help~

o, i find it at /dev/block/platform/soc/a600000.ssusb/a600000.dwc3/xhci-hcd.0.auto/sdg1 and /dev/block/sdg1

**Comment by exalab999** [comment]
I never tried this but I think you need rooted device for this operation.
