### ISSUE TITLE
On attempting to install anything with apt this happens

### ISSUE THREAD

**Issue by flashgnash** [EXALAB/AnLinux-App#36]
I've read about some similar problems on https://github.com/Neo-Oli/termux-ubuntu/issues/44 this github. It also happens when I try to install the vnc server and desktop with the commands provided

```E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
E: Method gave invalid 400 URI Failure message: Failed to set new group ids - setresgid (38: Function not implemented)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)```

**Comment by exalab999** [comment]
This is a long exist issue that occur when running Linux distro on Termux, currently we are investigate it, I think it might be some sort of container issue. We will try and fix it in the upcoming release, if possible

**Comment by smilearric** [comment]
Following #37 I'm posting here to get suscribed and notified in case some help is required here.

**Comment by qas** [comment]
Same issue on my Pixel 3

**Comment by KnightBlood** [comment]
Same problem with a Xiaomi 8  (Android 9.0)

**Comment by jbourod** [comment]
Same problem on my OnePlus 5T (Android 9.0)

**Comment by roymwash** [comment]
not working on android P

**Comment by ExtosNex** [comment]
same here. Xiaomi Mi A1 (Android 9)

**Comment by rudolphpienaar** [comment]
+ OnePlus 6T (Android 9).

Also on every distro I've tried on termux -- debian and arch. Anything that tried to set gid or uid fails.

**Comment by castillo055** [comment]
Any progress with this issue?

**Comment by diehard88** [comment]
same thing here after my note 8 was upgraded to Pie.
My other devices still on oreo do not experience this.

**Comment by Kilo-411** [comment]
Im getting Error also

fixing shebang of start-kali.sh
making start-kali.sh executable
removing image for some space
You can now launch Kali with the ./start-kali.sh script
$
$ ./start-kali.sh
proot info: vpid 1: terminated with signal 11
$

**Comment by Kilo-411** [comment]
Not working on oreo either

**Comment by Kilo-411** [comment]
Im in but here is the msg............



: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
$ echo "export PROOT_NO_SECCOMP=1" >> .bashrc && hash -r
$ ./start-kali.sh                                 proot info: vpid 1: terminated with signal 11
$ /bin/bash
$ ./start-kali.sh
bash: [: : integer expression expected
root@localhost:~#
