### ISSUE TITLE
unable to update arch linux

### ISSUE THREAD

**Issue by lakhininenina** [EXALAB/AnLinux-App#363]
@exalab999 @licaon-kter @supersonictw @AnonaWolf @sisiravijaym 
pacman -Syu
:: Synchronizing package databases...
 core.db failed to download
error: failed retrieving file 'core.db' from mirror.archlinuxarm.org : Could not resolve host: mirror.archlinuxarm.org
warning: too many errors from mirror.archlinuxarm.org, skipping for the remainder of this transaction
error: failed to synchronize all databases (invalid url for server)

**Comment by supersonictw** [comment]
Please check the mirror server of <mirror.archlinuxarm.org> is online in your region.

**Comment by lakhininenina** [comment]
@

> Please check the mirror server of <mirror.archlinuxarm.org> is online in your region.

got it. btw, my browser complains about only http version of mirror.archlinuxarm.org. does yours?
