### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by veraahmad** [EXALAB/AnLinux-App#382]
Hello, I'm new to termux and I tried to install Linux in termux and every time I fail, Linux is not installed in my termux, even though it's the latest version, is there a mistake from me or from the termux itself, I don't know I want help from an expert in termux and Linux

**Comment by LinXwinroot** [comment]
I am also experiencing the same problem in termux concernen "change dir"

**Comment by veraahmad** [comment]
The damaged tools are still on the site, I emailed support to no avail,
what's the solution?'؟

في السبت، ٢٢ أكتوبر ٢٠٢٢ ٩:٢٧ ص LinXwinroot ***@***.***> كتب:

**Comment by veraahmad** [comment]
Hello support team I want to file a complaint about the tools, most of them
are damaged, disabled, hands I find the tools that work

في السبت، ٢٢ أكتوبر ٢٠٢٢ ١:٣٦ م Veera Ahmad ***@***.***> كتب:

**Comment by exalab999** [comment]
I checked and the scripts are still working, could you please post screenshots so I know what is the problem?
