### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by Reddysan1433** [EXALAB/AnLinux-App#386]
![Screenshot_20220914-074155.jpg](https://user-images.githubusercontent.com/109979094/190043112-c8991441-8d35-47cd-a46c-b256757df8cd.jpg)

![Screenshot_20220914-074235.jpg](https://user-images.githubusercontent.com/109979094/190043130-4125fe59-ba04-4f3b-8510-61ab72ffa982.jpg)

Wt is this

**Comment by augustt0** [comment]
I'm having the same problem

**Comment by exalab999** [comment]
This bug is currently fixed, the issue is lacking dbus-x11 package, the new Desktop Environment script come now include dbus-x11.
