### ISSUE TITLE
Fedora dnf/yum install err

### ISSUE THREAD

**Issue by Zel9278** [EXALAB/AnLinux-App#4]
I am in trouble because I can not install everything.
![smartselect_20181020-131457_vnc viewer](https://user-images.githubusercontent.com/43949163/47251824-8c4dbd80-d474-11e8-81e4-6cff598a1b84.jpg)

**Comment by exalab999** [comment]
Try to run this command:

`setenforce 0`

This will disable the error if it is caused by SELinux, you could see if SELinux is in enforcing mode by running `sestatus` and check the Current Mode .

**Comment by Zel9278** [comment]
> This will disable the error if it is caused by SELinux, you could see if SELinux is in enforcing mode by running `sestatus` and check the Current Mode .

`[root@localhost ~]# setenforce 0
setenforce: SELinux is disabled`

**Comment by supersonictw** [comment]
I am sorry that I told @exalab999 the wrong solution.

We will check the bug asap ：(

**Comment by supersonictw** [comment]
I tested that installing nodejs with dnf and then there is no problem...
Maybe you can try reboot your device or reinstall the application
If it still error, leave your e-mail for us to asking your logs, thank you ^^
![screenshot_2018-10-20-20-35-16](https://user-images.githubusercontent.com/13705584/47255718-f3d13080-d4a7-11e8-98fa-e7b7a3529d90.png)

**Comment by Zel9278** [comment]
> I tested that installing nodejs with dnf and then there was no problem...
> Maybe you can try reboot your device or reinstall the application
> If it still show errors, leaving your e-mail for us
> We will ask for your system logs
> Thank you ^^
> ![screenshot_2018-10-20-20-35-16](https://user-images.githubusercontent.com/13705584/47255718-f3d13080-d4a7-11e8-98fa-e7b7a3529d90.png)

After rebooting, dnf can not be used.

**Comment by supersonictw** [comment]
To remove Termux maybe can help you to solve your problem but you data will be lost. :(
Could you leave your email or SNS for contacting?

**Comment by exalab999** [comment]
@truboxl Just updated amd64 and arm64 to Fedora 29, but armhf could not be update as the docker image in official repo is still 27...
