### ISSUE TITLE
vnc fails to start

### ISSUE THREAD

**Issue by ghost** [EXALAB/AnLinux-App#401]
@supersonictw @exalab999 provide installation method similar to "SSH".

right now there are only 2 things which are stopping me to abandon userland pp

- **vncserver-start: command not found**: on google play store comment by Jesse Ziegler on November 2, 2022. DO YOU HAVE INTENTION TO FIX THIS ISSUE? (i tried couple of times myself, perhaps i didnt know exact method or trick? 
- **vnc server installation method** similar to SSH on app. i am running debian bullseye with twm & i have no issues (of course on userland app......) please DONT provide installation method unless vnc server start & stop **is fixed**??????

**Comment by exalab999** [comment]
![Screenshot_2022-11-09-10-15-32-132_com.termux.jpg](https://user-images.githubusercontent.com/33449553/200721483-1ed1ece7-2434-42ed-8eb3-cb793de1a897.jpg)
![Screenshot_2022-11-09-10-15-42-572_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/33449553/200721500-81e5eeb0-e3fe-471c-86df-dacae4bedd2f.jpg)
@jindam-vani 
I just started a new fresh install, there are no problem about vncserver, tested in Debian bullseye with Xfce4.

However I do find a bug that desktop environment now need dbus-x11 to run and fixed it just now.

Could you try to check if the file vncserver-start exost by running: `which vncserver-start`

and then post the screenshots?

By the way just to make sure, you do know all the SSH and Desktop Environment command should only run after you fires up the distro by running `./start-debian.sh` first right?
