### ISSUE TITLE
[feature request] vnc server stand-alone installation method

### ISSUE THREAD

**Issue by jindam-vani** [EXALAB/AnLinux-App#402]
* is it possible to start vnc session without installing desktop environment?
* **if no**, provide stand-alone vnc server installation similar to SSH.

**note**: right now i am using twm on debian bullseye (userland app). twm is enough for me.

first requseted on #401 but the focus of the issue shifted to vnc start issue

twm: https://en.wikipedia.org/wiki/Twm

**Comment by exalab999** [comment]
@jindam-vani 

It was designed to be blank since it only contain vnc server.

If you need it to work with twn, simply install twm using

`apt install twm`

then stop the vncserver:

`vncserver-stop`

and restart it:

`vncserver-start`

This should be able to run twm when vnc started, if this doesn't work, try to edit `~/.vnc/xstartup` file and replace startx to the command that start twm.

**Comment by exalab999** [comment]
To @jindam-vani and everyone who come here to search how to install TWM, this will not be added as new feature, but a script has been added to install twm on apt based distro:

`wget https://github.com/EXALAB/Anlinux-Resources/raw/master/Beta/window_manager/apt/TWM/de-apt-twm.sh && bash de-apt-twm.sh`

This script is for apt based distro only, and it will **NOT** be removed from repo in the future.

**Comment by exalab999** [comment]
@jindam-vani You type the command wrong... The url is `window_manager`, not `windowmanager`. Please Double check before reporting to devs. Just copy the command instead of typing to prevent this error.

**Comment by exalab999** [comment]
@jindam-vani sorry my bad, fixed it now and should work.

**Comment by exalab999** [comment]
@jindam-vani Do you noticed that it still show `windowmanager` in the script? Delete the original script and try again: rm de-apt-*.sh

**Comment by exalab999** [comment]
Glad it works now, and thank you very much for pointing out the error in the scripts :smile:
