### ISSUE TITLE
bash ubuntu.sh not found

### ISSUE THREAD

**Issue by st3v3nholo** [EXALAB/AnLinux-App#42]
downloaded fine till entering ubuntu.sh in bash

skipping downloading
writing launch script
fixing shebang of start-ubuntu.sh
making start-ubuntu.sh executable
removing image for some space
rm: can't remove 'ubuntu-rootfs.tar.gz': No such file or directory
You can now launch Ubuntu with the ./start-ubuntu.sh script
$ ./start-ubuntu.sh
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 50035
root@localhost:~# ubuntu.subuntu.sh
bash: ubuntu.subuntu.sh: command not found
root@localhost:~# ubuntu.sh
bash: ubuntu.sh: command not found
root@localhost:~# start-ubuntu.sh
bash: start-ubuntu.sh: command not found
root@localhost:~# sudo
bash: sudo: command not found
root@localhost:~# pkg install wget proot -y && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh && bash ubuntu.sh
bash: pkg: command not found
root@localhost:~# ./start-ubuntu.sh
bash: ./start-ubuntu.sh: No such file or directory
root@localhost:~#

**Comment by exalab999** [comment]
Hi,

You have already enter Ubuntu by runnning start-ubuntu.sh, so why you run
it again?


Regards, EXA Lab
