### ISSUE TITLE
ssh username and password

### ISSUE THREAD

**Issue by wbhuangxm** [EXALAB/AnLinux-App#44]
When install desktop environment,   you are asked to  provide a vnc username and password 
However , when install ssh , no such action are required.
OpenBSD Secure Shell Server  seems to be installed successfully and can be launched. 
When I use an android ssh client, Termius, to connect to the server, A username is required. What is the username ? I have tried " root", but failed.

**Comment by exalab999** [comment]
Closed as duplicate of #41
