### ISSUE TITLE
There seems to be a typo

### ISSUE THREAD

**Issue by EddieKidiw** [EXALAB/AnLinux-App#441]
404: Not Found [Rootfs/CentOS/${archurl}/centos_stream-rootfs-${archurl}.tar.xz](https://github.com/EXALAB/Anlinux-Resources/blob/cda45e7aba3f5c9afc8b10f9886502ee22c2e01e/Scripts/Installer/CentOS/centos_stream.sh#L27)

amd64 [Rootfs/CentOS/amd64/centos-rootfs-amd64.tar.xz](https://github.com/EXALAB/Anlinux-Resources/commit/cda45e7aba3f5c9afc8b10f9886502ee22c2e01e#diff-89ee1dde77619cfc316b7d3e7d95ef793ca713e004f25f52fdb6869d058f29a8)

arm64 [Rootfs/CentOS/arm64/centos-rootfs-arm64.tar.xz](https://github.com/EXALAB/Anlinux-Resources/commit/cda45e7aba3f5c9afc8b10f9886502ee22c2e01e#diff-9be9f11a107d433b230f1d740cd5e402f4c87dcaf308abe57c0ddf3559d099c5)

**Comment by exalab999** [comment]
Thanks for reporting, the bugs have been fixed.
