### ISSUE TITLE
can't start vnc server on arch linux and lxde 

### ISSUE THREAD

**Issue by AndreyDeimos** [EXALAB/AnLinux-App#452]
When installing lxde on arch linux using the command provided by the app it says `usage: vncserver <display>.` I installed lxde and tigervnc not from the script and run vncserver :1. This is the result:
`
[root@localhost ~]# vncserver :1
Using desktop session LXDE

New 'localhost:1 ()' desktop is localhost:1

Starting desktop session LXDE

/usr/bin/Xvnc: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error
`
How can i fix this?
Edit: i installed libbsd and now it is giving me this:
[root@localhost ~]# vncserver :1
Using desktop session LXDE

New 'localhost:1 ()' desktop is localhost:1

Starting desktop session LXDE

Xvnc TigerVNC 1.13.1 - built May  2 2024 00:56:15
Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12101013

Thu Jun 20 09:17:17 2024
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
[mi] mieq: warning: overriding existing handler (nil) with 0x30001ebdb0 for event 2
[mi] mieq: warning: overriding existing handler (nil) with 0x30001ebdb0 for event 3
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
Running X session wrapper
Loading profile from /etc/profile
Loading xinit script /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
Failed to connect to bus: No medium found
dbus-update-activation-environment: error: unable to connect to D-Bus: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
X session wrapper complete, running session /usr/bin/startlxde
/usr/bin/lxsession: symbol lookup error: /usr/lib/libpango-1.0.so.0: undefined symbol: g_once_init_leave_pointer
xinit: connection to X server lost

waiting for X server to shut down  ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:nan ratio)

**Comment by Cmcmk11** [comment]
I have the same issue. I got arch installed and had to install a vnc as above poster. Same results.

**Comment by zerobikappa** [comment]
https://github.com/EXALAB/Anlinux-Resources/blob/cdd3f7d4a6908494216bc3bffa7c790d9d4c693c/Scripts/DesktopEnvironment/Pacman/de-pac.sh#L4

This command did not run because `dbus-x11` was already deprecated and replaced by `dbus`. As a result, system did not install `lxde` and `tigervnc` as well.

**Comment by exalab999** [comment]
Fixed the issue by changing from dbus-x11 to dbus
