### ISSUE TITLE
Ubuntu can't start 

### ISSUE THREAD

**Issue by milen-prg** [EXALAB/AnLinux-App#459]
~ $ ./start-ubuntu.sh
proot warning: can't sanitize binding "ubuntu-fs/root": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
~ $

**Comment by xmexg** [comment]
https://github.com/EXALAB/AnLinux-App/issues/456  

Do not download termux from the Play Store

We should download termux from this URL
https://github.com/termux/termux-app/releases
