### ISSUE TITLE
Support Musl

### ISSUE THREAD

**Issue by fervi** [EXALAB/AnLinux-App#46]
Hello. 

Libc6 in most distros required Kernel 3.2, but some phones have older kernel. Technically this distros (like Debian) should work with Musl (Libc6 alternative). Maybe AnLinux should support also this?

**Comment by exalab999** [comment]
Usually AnLinux only run on device with Android 5+.

According to [Android Version History on Wikipedia](https://en.wikipedia.org/wiki/Android_version_history), Android 5+ is running 3.16 Kernel, which is supported currently. However we will take this into consideration in the future development.

**Comment by fervi** [comment]
I understand, but some modders create ports for older devices, for example you have Replicant 6.0 or LineageOS 7.0 with 3.0 kernel
