### ISSUE TITLE
package ------ does not have a compatible architecture / Fedora DNF Error

### ISSUE THREAD

**Issue by Zel9278** [EXALAB/AnLinux-App#47]
I attempted to install software from storage like images, but I got an error.
![screenshot_20190114-135627_vnc viewer](https://user-images.githubusercontent.com/43949163/51097046-7eee6800-1804-11e9-90f6-212db52ceca5.jpg)

**Comment by exalab999** [comment]
This usually occur when using wrong architecture rpm package.

Could you please try to run: 

`uname -a`

and provide the output?

**Comment by Zel9278** [comment]
> This usually occur when using wrong architecture rpm package.
> 
> Could you please try to run:
> 
> `uname -a`
> 
> and provide the output?

[root@localhost ~]# uname -a
Linux localhost 4.9.65-14702331 #1 SMP PREEMPT Fri Nov 2 20:41:59 KST 2018 aarch64 aarch64 aarch64 GNU/Linux

**Comment by exalab999** [comment]
Your device architecture is aarch64, not x86_64, Atom editor currently does not support arm and arm64 device yet, please try to use another editor.

**Comment by Zel9278** [comment]
> Your device architecture is aarch64, not x86_64, Atom editor currently does not support arm and arm64 device yet, please try to use another editor.

Ok,Thanks.
