### ISSUE TITLE
vncserver: The USER environment variable is not set.

### ISSUE THREAD

**Issue by Kymonlucky** [EXALAB/AnLinux-App#48]
When I tried to run "vncserver" it wont start it says:

vncserver: The USER environment variable is not set.

Im using ubuntu

**Comment by exalab999** [comment]
Hi, please follow the instruction.

The command is "vncserver-start", not "vncserver"

If you have for problem, please check the Documentation.


Regards, EXA Lab

**Comment by Briwisdom** [comment]
try ‘sudo vncserver’ please, it works to me.

**Comment by new4u** [comment]
> try ‘sudo vncserver’ please, it works to me.

thank you very much

**Comment by ledlamp** [comment]
USER=yourusername vncserver

**Comment by buildsomestuff** [comment]
None of the others worked for me except this one: "USER=yourusername vncserver"
Make sure you don't immediately dismiss it for copying and pasting, yoursuername should be replaced with your user name. 
:)

**Comment by otabekrizayev** [comment]
I did not see any user departures during the installation process.  but I set a password but no user.  Which command can be used to install a user on a vncserver?
![Screenshot_20201222-141948_VNC Viewer](https://user-images.githubusercontent.com/46789195/102871874-c950d880-4460-11eb-919f-9be1202a8491.jpg)
      ######![Screenshot_20201222-141919_Termux](https://user-images.githubusercontent.com/46789195/102871906-d4a40400-4460-11eb-9097-4fe268eb0111.jpg

**Comment by ANONYMOUS-00700** [comment]
> > try ‘sudo vncserver’ please, it works to me.
> thanks a lot buddy

**Comment by hasanghasemi** [comment]
hello 
 my termux kali is set to perevius pichare up oky.
now what in comand line for run

**Comment by hasanghasemi** [comment]
sudo not run in kali termux error

**Comment by Arjukp** [comment]
vncserver: The USER environment variable is not set.
Help me to solve this

**Comment by hectorjosh** [comment]
![Screenshot_20230211-113450.png](https://user-images.githubusercontent.com/105675043/218248734-369dfb69-4eff-47d4-b47b-b6ebb0394eed.png) I can't see the gui

**Comment by Alexey808** [comment]
В моём случае без export не работало
export USER=YOUR_USER_NAME

Проверить что в USER переменной можно так
env | grep USER
