### ISSUE TITLE
Need to rm -rf /tmp/* to restart VNC

### ISSUE THREAD

**Issue by MasterDevX** [EXALAB/AnLinux-App#52]
Every time I stop VNC server I need to rm -rf some files in tmp directory to start it again. If I won't do that I'll be unable to connect to the VNC. It is somewhat uncomfortable and annoying to do this so often, so I think it makes sense to make something that will run following command automatically after vncserver-stop.

**Comment by exalab999** [comment]
Thanks for recommend, it has been fixed just now.
