### ISSUE TITLE
Fedora - dnfdragora and Web Browsers Not Working

### ISSUE THREAD

**Issue by Bestrafung** [EXALAB/AnLinux-App#54]
I'm new to AnLinux but so far it's been good. The only issue I have noticed is that dnfdragora seems to crash before opening and I haven't been able to get any web browser working. Obviously this isn't a major issue since dnf can be run via terminal and I can use the browser on the phone but I would like to try to resolve this if possible. I've created a list of browsers tried as well as a description of the error for each. Any assistance would be appreciated.

Chrome: Every attempt to install via dnf and yum has failed with package not found errors
Chromium: Crashes immediately upon launch (no visual evidence except in Task Manager)
Firefox: Displays just a black window, no UI and unusable
Midori and Gnome Web: UI appears complete and pages seem to load in the background but still nothing displayed in the window
![midori](https://user-images.githubusercontent.com/5366399/51797466-56864680-21d2-11e9-86e0-b0e83fba7bb7.jpg)
![epiphany](https://user-images.githubusercontent.com/5366399/51797467-571edd00-21d2-11e9-9c7d-c554f42ce0c1.jpg)
![firefox](https://user-images.githubusercontent.com/5366399/51797468-571edd00-21d2-11e9-947f-efafab91f63d.jpg)

**Comment by exalab999** [comment]
Currently Midori browser work best with AnLinux, Firefox always result in black screen, and chrome are not test yet.

For the blank problem about Midori, please try using the Patches feature in the AnLinux and see if it could be fixed.

**Comment by Zel9278** [comment]
![screenshot_20190129-175617_termux](https://user-images.githubusercontent.com/43949163/51896259-65961000-23ef-11e9-8d85-e937e2c2bbce.jpg)
I tried a patch, but if I run it I will throw an error.
(I'm sorry midway)

**Comment by exalab999** [comment]
@Zel9278 No, it should not be used like that. First start the distro by running `./start-*.sh`, then run the Patch when you want to run the program, for example:

`env LD_PRELOAD="/usr/local/lib/libandroid-shmem.so" midori`

**Comment by Zel9278** [comment]
> @Zel9278 No, it should not be used like that. First start the distro by running `./start-*.sh`, then run the Patch when you want to run the program, for example:
> 
> `env LD_PRELOAD="/usr/local/lib/libandroid-shmem.so" midori`

![screenshot_20190129-181901_vnc viewer](https://user-images.githubusercontent.com/43949163/51897635-8dd33e00-23f2-11e9-89af-bf490eb45581.jpg)

**Comment by sujitvasanth** [comment]
I got chromium to work in fedora on aarch64 you need a no-sandbox switch..it gives errors but then works perfectly.  from the terminal or from a desktop shortcut: usr/bin/chromium-browser --no-sandbox

I could not install chromium on ARM7h1 (eg. amazon fird 8 hd tablet)  or ARM 32 bit(e.g. Lenovo tab 10)  but firefox works on both  of these out of the box in fedora mate

**Comment by exalab999** [comment]
This issue has been solved [#21](https://github.com/EXALAB/AnLinux-App/issues/21), please fully uninstall using the Uninstall feature in app, then reinstall it to solve this issue.
