### ISSUE TITLE
Extraction of arch-root.tar.gz fails in version 5.10 on Fairphone2 (ver 18.10.0, Android 7.1.2)

### ISSUE THREAD

**Issue by CCmesch** [EXALAB/AnLinux-App#55]
Problem:  it is kind of similar like the "Can't start Arch Linux #45" issue, but prevails after that issue being closed.
The problem: Whilst using the provided command to download the _arch-root.tar.gz_ file (name might be slightly different, but you know which one) with over 200MB and the arch.sh script, there is an error at that point when the arch.sh script is being called and attempts to extract the tarfile into _./arch-fs/_ folder. 
The command is something like  "_proot  -l tar  arch-root.tar.gz  || :_  "
Here proot fails with an error message, something with " ... 9". 
Then the tarfile is deleted as planned via the script (for space reasons) and the next error message is like the one in "Can't start Arch Linux #45" issue, which is logical, because there are no files in "_arch-fs/_"

I tried a workaround myself, changing the arch.sh script, so it didn't delete the tarfile, and tried extracting it myself with tar, only to find out that the "tar" command could not be called because it wasn't found when starting   "proot -l tar  _tarfile_  _folder_ "
There is a tar program installed in /system/bin/tar , but it is not found. That MIGHT be the problem, but I don't know". But the files are definitely NOT extracted into arch-fs/ .
I did not call it as root, as you say that is not necessary.

Please take a look.

Another issue is when choosing the suse linux option instead, there not even the tarfile is downloaded for some reason, I don't know why. It probably isn't found at the server location specified. A network error on my side is unlikely because the script suse.sh is downloaded all right. You might want to check if it all works.

Cheers,

CCmesch

**Comment by jrd** [comment]
Proot is not working on the FP2 arch or maybe the kernel configuration.

`proot true` failed

**Comment by exalab999** [comment]
Thanks for reporting the bugs! It has been fixed.
