### ISSUE TITLE
Arch Linux/ corrupted packages with invalid gpg key

### ISSUE THREAD

**Issue by gabx** [EXALAB/AnLinux-App#58]
When upgrading the system after a fresh install with the `# pacman -Syu` command,you will find many errors like this one:
```
error: vim-runtime: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/vim-runtime-8.1.0022-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
```

To solve this issue, run again the following commandst:
```
# pacman-key --init
# pacman-key --populate archlinuxarm
```

See this [arch arm forum post](https://archlinuxarm.org/forum/viewtopic.php?f=65&t=12796)

**Comment by exalab999** [comment]
This command is included in the Arch Linux Desktop Environment command, I will add it to the Documentation, thanks for remind.
