### ISSUE TITLE
Error while configuring udisk2

### ISSUE THREAD

**Issue by 4li77l3n00b** [EXALAB/AnLinux-App#60]
root@localhost:~# dpkg --configure -a
Setting up udisks2 (2.8.1-3) ...
Failed to scan devices: No such file or directory
dpkg: error processing package udisks2 (--configure):
 installed udisks2 package post-installation script subprocess returned error exit status 1

**Comment by KthulhuFtaghn** [comment]
still no fix? only solution i found so far is to uninstall udisks2 and friends (gvfs etc)

**Comment by exalab999** [comment]
The only way to do this is to uninstall udisks2 package, the DE Scripts now automatically uninstall default file manager: 
`apt-get remove udisks2 thunar -y
apt-get install xfe
apt-get clean`

**Comment by KthulhuFtaghn** [comment]
thx for the help

**Comment by KthulhuFtaghn** [comment]
any idea how i can get an otg/usb wlan dongle working on android with
kali/parrot/etc?

**Comment by KthulhuFtaghn** [comment]
also i get a display error when i run the vnc with lxde in parrot. ill send
u a screenshot

**Comment by Footsiefat** [comment]
Still have this problem on newest version 😬
