### ISSUE TITLE
Error about Proot signal 6, or function not implemented error

### ISSUE THREAD

**Issue by exalab999** [EXALAB/AnLinux-App#61]
Looks like currently PRoot not work well with Some China Manufacture device.

Currently won't work: Huawei
Still works: OPPO
Untested, but still received some error report: Xiaomi

If you have any solution or info, please don't hesitate to post here.

**Comment by CubicFace** [comment]
You answered yourself at https://github.com/EXALAB/AnLinux-App/issues/30
It worked well on Honor 8X (JSN-L21)
Just put the command in the Termux .bashrc file and done.
