### ISSUE TITLE
How to change screen resolution in vnc server

### ISSUE THREAD

**Issue by apandada1** [EXALAB/AnLinux-App#63]
I am using ubuntu with XFCE . The default screen resolution app in xfce does not work.
How to change the default 1024x768 resolution?

**Comment by exalab999** [comment]
Thanks for reminding me, I have create a wiki page for this so other users could easier found their solution:

[How to change the resolution of VNC Server](https://github.com/EXALAB/AnLinux-App/wiki/How-to-change-the-resolution-of-VNC-Server)
