### ISSUE TITLE
Copy anlinux installation to another device

### ISSUE THREAD

**Issue by sujitvasanth** [EXALAB/AnLinux-App#67]
It takes several hours to prepare a distribution and get everything working. Is it possible to port the installation to a second device? and would this overcome some installation issues on oreo? 

also is it possible to have more than one distribution on one device?
i.e. can you somehow have 2 copies of anlinux on a single device?

**Comment by exalab999** [comment]
I've write a guide on [wiki](https://github.com/EXALAB/AnLinux-App/wiki/How-to-backup-and-move-Linux-distro-to-another-device) about this.

**Comment by sujitvasanth** [comment]
thank-you so much!
i wonder if uts possible to copy the files directly over a network __

**Comment by exalab999** [comment]
No problem, updated [wiki](https://github.com/EXALAB/AnLinux-App/wiki/Is-it-possible-to-install-multiple-distro-on-a-device-%3F)
