### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by jimchen5209** [EXALAB/AnLinux-App#70]
Parrot Security OS seems to be stacked together with backbox when selecting OS in installing SSH page
![screenshot_20190303-142410](https://user-images.githubusercontent.com/10269287/53691813-6fc97680-3dc0-11e9-9eae-3307bb41c49c.png)

O.S.: Android pie
Language: Chinese Traditional

**Comment by exalab999** [comment]
This has been fixed in v5.32, please update the app:

[v5.32](https://github.com/EXALAB/AnLinux-App/releases/download/v5.32/app-release.apk)
