### ISSUE TITLE
Disabling SSL due to encountered errors

### ISSUE THREAD

**Issue by TIBTHINK** [EXALAB/AnLinux-App#71]
I cant install any OS's and I get this error 
Anyone know why

**Comment by gates19** [comment]
i guess it's not only me then..
sorry did not see this thread

but i think it has something to do with the latest update <Google PlayStore>

**Comment by exalab999** [comment]
Hi, this is the error of wget, it has nothing to do with AnLinux. Please
wait for Termux team to update the wget package.


Regards, EXA Lab

**Comment by exalab999** [comment]
Hi, a new release has fixed this problem: termux/termux-packages#3426
<https://github.com/termux/termux-packages/issues/3426>

It recently wget update require openssl-tool but that package doesn't
include as a dependencies of wget, so I have update the AnLinux command to
install it automatically, which should fix this problem.


Regards, EXA Lab
