### ISSUE TITLE
Unable to uninstall Kali distro because ssl issue

### ISSUE THREAD

**Issue by lolhelloeddie** [EXALAB/AnLinux-App#74]
I'm trying to uninstall termux because the Kali distro is taking alot of my internal storage in my phone but I keep getting this error message. Can you please help. Thank you.
![screenshot_2019-03-04-13-20-20](https://user-images.githubusercontent.com/16203002/53763770-6dc6ec80-3e80-11e9-8045-b482a9ed98ac.png)

**Comment by exalab999** [comment]
Hi, this is  an error of wget, which is not a problem of AnLinux, just wait
for Terkux team to fix it.

However, you could still uninstall Kali by two ways:

1. Reinstall Termux

2. Clear data of Termux


Regards, EXA Lab

**Comment by exalab999** [comment]
Fixed in v5.35, for more info, check the release change log.
