### ISSUE TITLE
Vncserver not working

### ISSUE THREAD

**Issue by ashwingole** [EXALAB/AnLinux-App#75]
I had installed ubuntu(xfce4) and ubuntu mate as well i tried to start vncserver the following message shows up-

Warning: localhost:1 is taken because of /tmp/.X11-unix/X1
Remove this file if there is no X server localhost:1
A VNC server is already running as :1
root@localhost:~# vncserver-start

What should i do??

**Comment by exalab999** [comment]
just follow the instruction, run this command:

`rm -rf /tmp/.X11-unix/X1`
