### ISSUE TITLE
Cannot run Backbox Linux

### ISSUE THREAD

**Issue by Poincare1** [EXALAB/AnLinux-App#79]
Backbox Linux installs without error but it will not run. When I execute ./start-backbox.sh the following errors are generated every time:

$ ./start-backbox.sh
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 20165
groups: cannot find name for group ID 50165
root@localhost:~#

**Comment by exalab999** [comment]
Hi, please don't worry about this it is just a harmless warning, you could get rid of it by running this command inside BackBox shell:

`touch ~/.hushlogin`

We forgot to fix this issue, but no worries, we will fix this right now!

**Comment by Poincare1** [comment]
OK. I issued that command. I no longer see the warnings.
