### ISSUE TITLE
Cross-arch

### ISSUE THREAD

**Issue by mirzaatifbaig** [EXALAB/AnLinux-App#8]
I wanted to use this app but before I mess up my system I wanted to ask If I could run x86 or x64 chroot or proot via it using arm or arm64 as host.

**Comment by josephworks** [comment]
Proot uses your phone Arch. There might be a way for proot to add multi Arch. If so, that would be an addition for AnLinux settings.

**Comment by exalab999** [comment]
This is currently impossible as Proot does not support this feature.
