### ISSUE TITLE
Backbox Linux XFCE4 Fails To Install

### ISSUE THREAD

**Issue by Poincare1** [EXALAB/AnLinux-App#80]
There appear to be several errors when pasting the XFCE4 Backbox script into Termux.  The errors seem to prevent XFCE4 from being fully installed.  This occurs every time the XFCE4 install script for Backbox Linux is pasted.  The errors are: 

Hit:1 https://termux.net stable InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package xfce4
E: Unable to locate package xfce4-terminal
E: Unable to locate package tightvncserver
mkdir: can't create directory '/data/data/com.termux/files/home/.vnc': File exists
--2019-03-10 07:16:49--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/xstartup
Resolving raw.githubusercontent.com... 151.101.148.133
Connecting to raw.githubusercontent.com|151.101.148.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 110 [text/plain]
Saving to: ‘/data/data/com.termux/files/home/.vnc/xstartup.6’

     0K                                                       100% 1.07M=0s

2019-03-10 07:16:49 (1.07 MB/s) - ‘/data/data/com.termux/files/home/.vnc/xstartup.6’ saved [110/110]

--2019-03-10 07:16:49--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/vncserver-start
Resolving raw.githubusercontent.com... 151.101.148.133
Connecting to raw.githubusercontent.com|151.101.148.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 98 [text/plain]
/usr/local/bin: No such file or directory
/usr/local/bin/vncserver-start: No such file or directory

Cannot write to ‘/usr/local/bin/vncserver-start’ (Success).
--2019-03-10 07:16:50--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/vncserver-stop
Resolving raw.githubusercontent.com... 151.101.148.133
Connecting to raw.githubusercontent.com|151.101.148.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 100 [text/plain]
/usr/local/bin: No such file or directory
/usr/local/bin/vncserver-stop: No such file or directory

Cannot write to ‘/usr/local/bin/vncserver-stop’ (Success).
chmod: /usr/local/bin/vncserver-start: No such file or directory
chmod: /usr/local/bin/vncserver-stop: No such file or directory
 
You can now start vncserver by running vncserver-start
 
It will ask you to enter a password when first time starting it.
 
The VNC Server will be started at 127.0.0.1:5901
 
You can connect to this address with a VNC Viewer you prefer
 
Connect to this address will open a window with Xfce4 Desktop Environment
 
 
 
Running vncserver-start
 
 
 
To Kill VNC Server just run vncserver-stop
 
 
 
./de-apt-xfce4.sh: line 39: /etc/profile: Read-only file system
./de-apt-xfce4.sh: line 40: /etc/profile: No such file or directory
./de-apt-xfce4.sh: line 42: vncserver-start: command not found

**Comment by exalab999** [comment]
Thanks for reporting, but this is not a bug, it just you don't follow the instruction correctly. **You must run it inside BackBox Shell**, which means you should run `./start-backbox.sh` first, then run the command above.

**Comment by Poincare1** [comment]
Oh!  I see how it is different now. Thanks for feedback.
