### ISSUE TITLE
Can't acces sdcard from ubuntu...

### ISSUE THREAD

**Issue by rakbar650** [EXALAB/AnLinux-App#82]
The desktop environment seems doesnt read my internal storage... So... How to mount my internal storage. ?
Thanks in advance...

**Comment by exalab999** [comment]
It is already available in the [Documentation](https://github.com/EXALAB/AnLinux-App/wiki/How-to-use--sdcard)

**Comment by rakbar650** [comment]
woah... it fixed... sorry for my ignorance...

**Comment by rakbar650** [comment]
And also... how to make the browser work ? When i open it... it shows "failed to execute default web browser. Input/output error"
