### ISSUE TITLE
Browser not working

### ISSUE THREAD

**Issue by meechdecoder** [EXALAB/AnLinux-App#88]
How to use browser in anlinux app dritro

**Comment by donchris1** [comment]
I am having the same problem right now. The error message I got is,

 "Failed to execute default Web browser. 
input/output error. "

Any suggestion(s) on how to resolve this?

**Comment by hjyoung1** [comment]
Same problem

**Comment by bpsib** [comment]
Have you tried installing a web browser? It could be because one isn't installed.

**Comment by donchris1** [comment]
I installed mozilla Firefox the app refuses to open

**Comment by bpsib** [comment]
It's a known issue with Firefox on AnLinux. See issue #21. It would be great if someone could workaround this issue and get Firefox working. I think the best thing for now is to try the Midori browser.

**Comment by anandhanking** [comment]
Use this following command to install firefox

apt-get install firefox-esr

Then open the browser...

**Comment by exalab999** [comment]
This issue has been solved [#21](https://github.com/EXALAB/AnLinux-App/issues/21), please fully uninstall using the Uninstall feature in app, then reinstall it to solve this issue.
