### ISSUE TITLE
Feature Request: Run x86 linux os on arm based phone using proot

### ISSUE THREAD

**Issue by Chinuminu11** [EXALAB/AnLinux-App#96]
Hello Developers,

Excellent job. The app works great on my device.
I would like to ask or suggest a feature which can be added to this app.
As per my knowledge proot can emulate x86 code on an arm based device and vice veras.
So will it be possible to install an x86 linux flavours instead of regular arm on android device.
     
Thanks in advance!
CAG

**Comment by exalab999** [comment]
I try this a lot with qemu, it run very slow on my computer with high specs, not sure PRoot could do this, but trying to run cross arch distro will make it very slow... So this option might not be considered.
